version: "3.7"

services:
  app:
    build: .
    volumes:
      - app:/app
    ports:
      - 3000:3000
    command: yarn next dev

volumes:
  app:

x-mutagen:
  sync:
    defaults:
      ignore:
        vcs: true
    app:
      alpha: "."
      beta: "volume://app"
